// Code generated by "stringer -type Location"; DO NOT EDIT.

package stack

func _() {
	_ = "STUB: not implemented"
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	return
}

const _Location_name = "LocationUnknownGoModGOPATHGoPkgStdliblastLocation"

var _Location_index = [...]uint8{0, 15, 20, 26, 31, 37, 49}

func (i Location) String() string { _ = "STUB: not implemented"; return "" }
