// Copyright 2017 Marc-Antoine Ruel. All rights reserved.
// Use of this source code is governed under the Apache License, Version 2.0
// that can be found in the LICENSE file.

//go:build tools

package main

import (
	"fmt"
	"os"
)

const content = `// Code generated by regen.go. DO NOT EDIT.

package stack

import (
	"html/template"
)

const indexHTML = {{.IndexHTML}}

// favicon is the bomb emoji U+1F4A3 in Noto Emoji as a 128x128 base64 encoded
// PNG.
//
// See README.md for license and how to retrieve it.
const favicon template.HTML = "{{.Favicon}}"
`

// loadGoroutines returns "goroutines.tpl" slightly processed for density.
func loadGoroutines() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// Strip out leading whitespace.

func mainImpl() error { _ = "STUB: not implemented"; return nil }

// See README.md how to generate it.

func main() {
	if err := mainImpl(); err != nil {
		fmt.Fprintf(os.Stderr, "Failed: %s\n", err)
		os.Exit(1)
	}
}
