// Code generated by "stringer -type state"; DO NOT EDIT.

package stack

func _() {
	_ = "STUB: not implemented"
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	return
}

const _state_name = "lookingdonebetweenRoutinegotRoutineHeadergotFuncgotCreatedgotFileFuncgotFileCreatedgotUnavailgotRaceHeader1gotRaceHeader2gotRaceOperationHeadergotRaceOperationFuncgotRaceOperationFilebetweenRaceOperationsgotRaceGoroutineHeadergotRaceGoroutineFuncgotRaceGoroutineFilebetweenRaceGoroutines"

var _state_index = [...]uint16{0, 7, 11, 25, 41, 48, 58, 69, 83, 93, 107, 121, 143, 163, 183, 204, 226, 246, 266, 287}

func (i state) String() string { _ = "STUB: not implemented"; return "" }
